### PR TITLE
2.3.0

### PR DESCRIPTION
**Pull request by annzenkina**

### CODE REVIEW

**Comment by WillSewell** [comment]
I'm concerned that

https://github.com/pusher/pusher-http-node/pull/104/files#diff-3deb3f32958bb937ae05c6f3e4abbdf5R7-R13

Would have introduced a breaking change in some versions of node. Could you provide an example of how it was broken previously, and how it behaves now?

**Comment by annzenkina** [comment]
previously there was one test which tested generated auth signature, and it was failing in CI with the versions <=10 (https://travis-ci.org/pusher/pusher-http-node/builds/562127170) or >=11 (https://travis-ci.org/pusher/pusher-http-node/builds/562097526). We didn't know about this before because we didn't test versions above 11 in CI

**Comment by annzenkina** [comment]
@WillSewell hm, you might be right.

**Comment by WillSewell** [comment]
Ah I see. So the function has never worked in node >= 11. In that case I don't think it's a breaking change.

I think this should be released as version 2.2.2. According to https://semver.org/, minor releases should only be for additions to the public API. This is just a fix.

**Comment by annzenkina** [comment]
@WillSewell yes, you're right. I over-panicked after your message and thought that i have changed the tests to let it pass, but i didn't. Yes, it never worked in >=11, as from that version the `sort` function work differently.

I will change it to the version 2.2.2 then.

**Comment by WillSewell** [comment]
Sorry for panicking you!

**Pull request closed without merging**
