### PR TITLE
support `cluster` option

### PR DESCRIPTION
**Pull request by topliceanu**
https://github.com/pusher/pusher-http-node/issues/24

### CODE REVIEW

**Comment by topliceanu** [comment]
CC @hamchapman @jpatel531

**Comment by hamchapman** [comment]
LGTM

**Comment by jpatel531** [comment]
LGTM too :)

**Comment by topliceanu** [comment]
Thanks Jamie

On Wed, Feb 17, 2016 at 3:59 PM, Jamie Patel <notifications@github.com>
wrote:

> LGTM too :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pusher/pusher-http-node/pull/25#issuecomment-185270616>
> .
>



-- 
Alexandru Topliceanu

**Pull request merged**
