### PR TITLE
Run tests with Travis-CI

### PR DESCRIPTION
**Pull request by zimbatm**
Helps us avoid regressions

### CODE REVIEW

**Comment by leggetter** [comment]
For any tests to run we need a `test` script in `package.json`.

See http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Default-Test-Script

**Comment by zimbatm** [comment]
Thanks I was struggling with that, waiting for the build to succeed

**Comment by vivangkumar** [comment]
It can also be specified in the `travis.yml` file under `script:`

**Comment by leggetter** [comment]
Can we do it in `package.json` please?

**Comment by zimbatm** [comment]
@leggetter it's using package.json to run the tests

**Comment by leggetter** [comment]
:+1:

**Pull request merged**
